USE [master];
CREATE SERVER AUDIT [AuditSpecification]
TO FILE 
(	FILEPATH = N'C:\audits\'
	,MAXSIZE = 50 MB
	,MAX_FILES = 4
	,RESERVE_DISK_SPACE = OFF
) WITH (QUEUE_DELAY = 1000, ON_FAILURE = CONTINUE, 
AUDIT_GUID = 'a39b90ef-dc26-486b-b297-1571161dfda1')
ALTER SERVER AUDIT [AuditSpecification] WITH (STATE = ON);
