USE Auditing;
ALTER DATABASE AUDIT SPECIFICATION [DatabaseAuditSpecification_Auditing] WITH (STATE = OFF); 
ALTER DATABASE AUDIT SPECIFICATION [DatabaseAuditSpecification_Auditing]
ADD (TRANSACTION_GROUP),
ADD (SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP);
ALTER DATABASE AUDIT SPECIFICATION [DatabaseAuditSpecification_Auditing] WITH (STATE = ON); 

USE master;
ALTER SERVER AUDIT SPECIFICATION [ServerAuditSpecification] 
WITH (STATE = OFF); 
ALTER SERVER AUDIT SPECIFICATION [ServerAuditSpecification]
ADD (LOGOUT_GROUP),
ADD (FULLTEXT_GROUP);
ALTER SERVER AUDIT SPECIFICATION [ServerAuditSpecification] 
WITH (STATE = ON); 
