USE [master]; 
CREATE SERVER AUDIT SPECIFICATION [miserverauditstorage]
FOR SERVER AUDIT [miauditstorage]
ADD (DATABASE_OBJECT_ACCESS_GROUP),
ADD (SCHEMA_OBJECT_ACCESS_GROUP),
ADD (AUDIT_CHANGE_GROUP),
ADD (SERVER_OPERATION_GROUP)
WITH (STATE = ON); 
