USE YourDBName; 
SELECT CT.SYS_CHANGE_VERSION, 
  CT.SYS_CHANGE_OPERATION, EM.* 
  FROM CHANGETABLE 
(CHANGES [AuditData],0) as CT 
LEFT JOIN [dbo].[AuditData] EM
ON CT.ID = EM.ID
ORDER BY SYS_CHANGE_VERSION; 
